---
title: "Final Project: Exploring Love Island USA Data"
format: gfm
---

# Background Information & Data Preparation

For my final project, I found a data set containing information on past Love Island USA contestants, aka 'islanders', from seasons 1-6. Love Island is a reality TV show where single people live in a villa in Fiji all summer while searching for love. While one group enters the villa on day 1, several more people are introduced into the mix as 'bombshells' throughout the season. In order to remain in the villa, islanders must be coupled up with a partner or they will be dumped. Each season ends with America voting for their favorite remainning couple as the winners. 

Loading the packages I am going to use:

```{python}
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
```

My data is a csv file that I downloaded from GitHub. 
Importing my data:

```{python}
love_island_df = pd.read_csv('C:/Users/Parri Salak/OneDrive/Documents/MSBA/Python/LoveIslandUSA.csv')
```

Cleaning column names to be in snake case:

```{python}
love_island_df.columns
love_island_df.columns = love_island_df.columns.str.strip().str.replace(' ', '_')
love_island_df.columns = love_island_df.columns.str.lower()
love_island_df.columns
```

# Data Exploration

Looking at the first 5 rows of data:

```{python}
love_island_df.head()
```

The data contains 190 rows, and 18 columns:

```{python}
love_island_df.shape
```

What types of information does the data contain:

```{python}
love_island_df.info()
```

## Age

One variable I would like to further explore is age. Most islanders that appear on the show are in their 20s, but what is their average age? Does this change across different groups, such as season, gender, or result?

The oldest islander was 32 years old at the time of their appearance on Love Island. This islander was Felipe Gomes:

```{python}
love_island_df['age'].max()
```

```{python}
oldest_islander = love_island_df[love_island_df['age'] == love_island_df['age'].max()]
oldest_islander['first_name'] + ' ' + oldest_islander['last_name']
``` 

The average age of contestants on Love Island is ~25 years old. However, the data also appear to be skewed right so median would be a better measure of center for this distribution:

```{python}
love_island_df['age'].mean()
```

```{python}
sns.histplot(data=love_island_df, x='age', bins=10)
plt.show()
```

Average age seems to have remained consistant across seasons, with season 3 having the highest average age and season 5 having the lowest:

```{python}
love_island_df.groupby('season')['age'].mean()
```

```{python}
sns.catplot(data=love_island_df, x="season", y="age", kind='box')
plt.show()
```

Female islanders have a slightly lower average age (24) then male islanders (25): 

```{python}
love_island_df.groupby('sex')['age'].mean()
```

```{python}
sns.displot(data=love_island_df, x='age', hue='sex',kind="kde")
plt.show()
```

The average age of winners does not differ from the overall average age of contestants:

```{python}
# Looking at winner as one result vs each other possible outcome
love_island_df.groupby('result')['age'].mean()
```

```{python}
# Looking at islanders being either a winner or loser
love_island_df['is_winner'] = love_island_df['result'].apply(lambda x: True if x == 'Winner' else False)

love_island_df.groupby('is_winner')['age'].mean()
```

## Location

Another variable I would like to explore is location. This is the city that each islander is currently living in before appearing on Love Island. 

There are 127 different locations where islanders come from:

```{python}
love_island_df['location'].nunique()
```

The most common city for islanders to be living in is Los Angeles, California with 16 contestants. This is most likely because producers host in-person recruiting for the show in LA:

```{python}
love_island_df['location'].value_counts().sort_values(ascending=False)
```

The data also contains a variable for the region of the United States that each contestant comes from:

```{python}
love_island_df['us_region'].value_counts()
```

```{python}
sns.countplot(love_island_df, x='us_region', order=love_island_df['us_region'].value_counts().index)
```

## Days in Villa

As more contestants enter the villa, islanders are forced to leave. I want to look at the minimum, maximum, and average amount of time spent in the villa.

The longest time spent in the villa was 39 days, and the shortest was only 2 days. The average time in the villa is around 14 days, or two weeks:

```{python}
love_island_df['days_in_villa'].describe()
```

```{python}
sns.histplot(data=love_island_df, x='days_in_villa', bins=15)
plt.show()
```

How does being in the first group in the villa change this? While the minimum and maxium do remain fairly consistant, the average amount of time spent in the villa for day 1 ('original') islanders is much higher at almost 24 days:

```{python}
love_island_df[love_island_df['first_group_in_villa'] == 'Yes']['days_in_villa'].describe()
```

```{python}
sns.catplot(love_island_df, x='days_in_villa', y='first_group_in_villa', kind='boxen')
plt.show()
```

## Conclusion

For this project, I explored historical Love Island USA data to answer question about islander's age, location, and time spent in the villa. To summerize, age remains consistant at ~25 years old across all groups. Most contestants come from the West coast of USA, and more specifically Los Angeles, CA. The average amount of time spent in the villa is two weeks, however those who were part of the original group of islanders each season were in the villa for much longer.  